
 const Days = [
    {
        id: 1,
        bodyPart: 'Legs & Abs',
        url: 'https://www.youtube.com/embed/QMfOJMmvS4Y',
        exercise: 
        {
            Leg_Press:'4 sets 8-12 reps',
            Split_Squats: '3 sets 8-12 reps',
            Hack_Squat: '3 sets 8-12 reps',
            Stiffed_Legged_Barbell_Deadlift:'4 sets 8-12 reps',
            Lying_Leg_Curl: '5 sets 8-12 reps',
            Seated_Calf_Raise: '4 sets 8-12 reps',
            Standing_Calf_Raise: '4 sets 8-12 reps',
            Bent_Knee_Hip_Raise: '4 sets 8-12 reps',
            Decline_Reverse_Crunch: '4 sets 8-12 reps',
            Cardio: '15 min (3 min easy 1 min hard)'
        },
        
    },
    {
        id: 2,
        bodyPart: 'Chest & Triceps',
        url: 'https://www.youtube.com/embed/sFlvqkAy-D0',
        exercise: {
            Incline_Dumbbell_Press: '3sets of 8-12 reps',
            Dumbbell_Bench_Press: '3 sets of 8-12 reps',
            Incline_Dumbbell_Flyes: '3 sets of 8-12 reps',
            Weighted_Dip: '3 sets of 8-12 reps',
            Triceps_Pushdown: '3 sets of 8-12 reps',
            Bent_Over_Cable_Triceps_Extension: '3 sets of 8-12 reps',
            Close_Grip_Barbell_Bench_Press: '4 sets of 8-12 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 3,
        bodyPart: 'Shoulders & Abs',
        url: 'https://www.youtube.com/embed/WfTJabJL1-w',
        exercise: {
            Cuban_Press: '4 sets of 8-12 reps',
            Side_Lateral_Raise: '3 sets of 8-12 reps',
            Front_Barbell_Raise: '3 sets of 8-12 reps',
            BentOver_Rear_Delt_Raise: '4 sets of 8-12 reps',
            Decline_Weighted_situp: '4 sets of 8-12 reps',
            Barbell_Rollout: '4 sets of 8-12 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 4,
        bodyPart: 'Back',
        url: 'https://www.youtube.com/embed/lfvYYA3iJBA',
        exercise: {
            Barbell_Row: '3 sets of 8-12 reps',
            Seated_Cable_Rows: '3 sets of 8-12 reps',
            Lat_Pulldown: '3 sets of 8-12 reps',
            OneArm_Dumbbell_Row: '3 sets of 8-12 reps per arm',
            Dumbbell_Pullover: '3 sets of 8-12 reps',
            Rack_Pulls: '3 sets of 8-12 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 5,
        bodyPart: 'Biceps & Abs',
        url: 'https://www.youtube.com/embed/2PywGKKZs9Y',
        exercise: {
            Barbell_Curl: '4 sets of 8-12 reps',
            Dumbbell_Alternate_Bicep_Curl: '4 sets of 8-12 reps',
            EZ_Bar_Curl: '4 sets of 8-12 reps',
            Seated_Calf_Press: '3 sets of 8-12 reps',
            Standing_Calf_Press: '3 sets of 8-12 reps',
            Bent_Knee_Hip_Raise: '4 sets of 8-12 reps',
            Jackknife: '4 sets of 8-12 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 6,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/HyNlQe4eWKc',
        exercise: {
            
        },
    },
    {
        id: 7,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/rp9_yAWgTbA',
        exercise: {
            
        },
    },
    {
        id: 8,
        bodyPart: 'Legs & Abs',
        url: 'https://www.youtube.com/embed/BraFwnxc11c',
        exercise: {
            Barbell_Squat: "2 sets of 14-18 reps",
            Wide_Stance_Barbell_Squat: "2 sets of 14-18 reps",
            Leg_Extensions: '4 sets of 14-18 reps',
            Hack_Squat: '4 sets of 14-18 reps',
            Seated_Calf_Raise: '5 sets of 18-20 reps',
            Crunch_Legs_On_Bench: '4 sets of oblique crunches and 10 regular crunches, 10 second hold between each set',
            Crunches: '4 sets of 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 9,
        bodyPart: 'Chest & Triceps',
        url: 'https://www.youtube.com/embed/y0OD5JHLOMY',
        exercise: {
            Incline_Dumbbell_Press: '4 sets of 14-18 reps',
            Dumbbell_Bench_Press: '4 sets of 14-18 reps',
            Incline_Dumbbell_Flyes: '4 sets of 14-18 reps',
            Incline_EZ_Bar_Skullcrushers: '3 sets of 14-18 reps',
            Weighted_Dips: '3 sets of 14-18 reps',
            Triceps_Pushdown: '3 sets of 14-18 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 10,
        bodyPart: 'Shoulders & Abs',
        url: 'https://www.youtube.com/embed/-wn25B1--dQ',
        exercise: {
            Seated_Dumbbell_Shoulder_Press: '4 sets of 18-20 reps',
            Seated_Side_Lateral_Raise: '4 sets of 18-20 reps',
            Dumbbell_Lying_Rear_Delt_Raise: '4 sets of 18-20 reps',
            Front_Incline_Dumbbell_Raise: '3 sets of 18-20 reps',
            Dumbbell_Shrug_Seated: '4 sets of 18-20 reps',
            Bottoms_Up: '6 sets of 18-20 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 11,
        bodyPart: 'Back',
        url: 'https://www.youtube.com/embed/q9gU_7VzjPw',
        exercise: {
            Lat_Pulldown_Warm_up: '2 sets of 18-20 reps',
            Pull_Up: '3 sets of absolute failure',
            Close_Grip_Pull_Up:'3 sets of absolute failure',
            One_Arm_Dumbbell_Row: '3 sets of 14-18 reps per arm',
            Leverage_Iso_Row: '3 sets of 14-18 reps',
            Wide_Grip_Lat_Pulldown: '3 sets of 14-18 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 12,
        bodyPart: 'Biceps & Abs',
        url: 'https://www.youtube.com/embed/hP_taxgdVSI',
        exercise: {
            Seated_Dumbbell_Curl_alternating: '3 sets of 14-18 reps',
            Preacher_curl: '3 sets of 14-18 reps',
            Lying_Cable_Curl: '3 sets of 14-18 reps',
            Standing_Calf_Raises: '4 sets of 18-20 reps',
            Cable_Crunch: '4 sets of 18-20 reps',
            Weighted_Crunches: '4 sets of 18-20 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 13,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/MfVZkcdrIXM',
        exercise: {
            
        },
    },
    {
        id: 14,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/gIW5j3NJCFk',
        exercise: {
            
        },
    },
    {
        id: 15,
        bodyPart: 'Legs & Abs',
        url: 'https://www.youtube.com/embed/x6t9s6HkXZo',
        exercise: {
            Leg_Press: "2 drop sets of 25-35 reps per drop",
            Dumbbell_Squat: "2 drop sets of 20-25 reps per drop",
            Leg_Extensions: '3 double drop sets of 15-20 reps per drop',
            Lying_Leg_Curls: 'Superset (1/2) 5 sets of 15-20 reps',
            Stiff_Legged_Dumbbell_Deadlift: 'Superset (2/2) 5 sets of 15-20 reps',
            Seated_Calf_Raise: 'Superset (1/2) 4 sets of 20-25 reps',
            Standing_Calf_Raise: 'Superset (2/2) 4 sets of 20-25 reps',
            Incline_Leg_Pull_In: 'Superset (1/2) 4 sets of 20 reps',
            Leg_Pull_In: 'Superset (2/2) 4 sets of 20 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',   
        },
    },
    {
        id: 16,
        bodyPart: 'Chest & Triceps',
        url: 'https://www.youtube.com/embed/5uOoo5FkNt8',
        exercise: {
            Smith_Machine_Incline_Bench_Press: '2 drop sets of 20-25 reps; 20-25 reps on each drop; 2 drops on second set',
            Smith_Machine_Bench_Press: '2 drop sets of 20-25 reps; 20-25 reps on each drop; 2 drops on second set',
            Incline_Dumbbell_Flyes: '3 drop sets of 15-20 reps; 15-20 reps on each drop',
            Cable_Crossover: '2 drop sets of 15-20 reps; 15-20 reps on each drop',
            Triceps_Pushdown: '3 sets of 15-20 reps',
            Bent_Over_Cable_Triceps_Extension: '3 sets of 15-20 reps',
            Dumbbell_Triceps_Extension: '3 sets of 20-25 reps',
            Close_Grip_Barbell_Bench_Press: '3 sets of 20-25 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 17,
        bodyPart: 'Shoulders & Abs',
        url: 'https://www.youtube.com/embed/3y3Dhg41Qeg',
        exercise: {
            Seated_Dumbbell_Shoulder_Press: 'Giant Set (1/3) 3 sets of 20-25 reps',
            Seated_Side_Lateral_Raise: 'Giant Set (2/3) 3 sets of 20-25 reps',
            Front_Dumbbell_Raise: 'Giant Set (3/3) 3 sets of 20-25 reps',
            Seated_Bent_Over_Rear_Delt_Raise: 'Superset (1/2) 4 sets of 20-25 reps',
            Side_Lateral_To_Front_Raise: 'Superset (2/2) 4 sets of 20-25 reps',
            Dumbbell_Shrug_Seated: '3 sets of 20-25 reps',
            Dumbbell_Weighted_Situp: '3 sets of 15-20 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 18,
        bodyPart: 'Back',
        url: 'https://www.youtube.com/embed/Ov_Bev5Tqls',
        exercise: {
            Bent_Over_Two_Dumbbell_Row: '3 sets of 15-18 reps; Last set is dropset for 15-18 reps',
            Lat_Pull_Down: 'Superset (1/2) 3 sets of 15-20 reps',
            Under_Hand_Cable_Pull_Down: 'Superset (2/2) 3 sets of 15-20 reps',
            Chest_Supported_Dumbbell_Row:'Superset (1/2) 3 sets of 15-20 reps',
            Straight_Arm_Pull_Down: 'Superset (2/2) 3 sets of 15-20 reps',
            Barbell_Deadlift: '3 sets of 15-20 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 19,
        bodyPart: 'Biceps & Calves & Abs',
        url: 'https://www.youtube.com/embed/AIJGLhdQvk4',
        exercise: {
            Wide_Grip_Standing_Barbell_Curl: '3 dropsets of 15-20 reps, 15-20 reps on drop',
            Close_Grip_Standing_Barbell_Curl: '3 sets of 15-20 reps, first set is a drop set for 15-20 reps',
            Seated_Calf_Raise: '15-20 reps, 15-20 reps on drop',
            Standing_Calf_Raises: '3 dropsets of 15-20 reps, 15-20 reps on drop',
            Incline_Reverse_Crunch: 'Superset (1/2) 3 sets of 15-20 reps',
            Exercise_Ball_Pulling: 'Superset (2/2) 3 sets of 15-20 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 20,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/uazFQVEVPnU',
        exercise: {
            
        },
    },
    {
        id: 21,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/G7c0-yMJ7g4',
        exercise: {
            
        },
    },
    {
        id: 22,
        bodyPart: 'Chest & Triceps',
        url: 'https://www.youtube.com/embed/_qbL07HeOnM',
        exercise: {
            Incline_Dumbbell_Press: '4 sets of 8-10 reps , 90-120 sec rest',
            Dumbbell_Bench_Press: '3 sets of 8-10 reps , 90-120 sec rest',
            Decline_Dumbbell_Bench_Press: '3 sets of 8-10 reps , 90-120 sec rest',
            Peck_Deck_Fly: '7 sets 8-10 reps, 30 sec rest',
            Reverse_Grip_Triceps_Push_Down: '4 sets of 8-10 reps , 90-120 sec rest',
            Close_Grip_Barbell_Bench_Press: '3 sets of 8-10 reps , 90-120 sec rest',
            Overhead_Dumbbbell_Triceps_Extension: '3 sets of 8-10 reps , 90-120 sec rest',
            Triceps_Pushdown_Rope_Attachment: '7 sets 8-10 reps, 30 sec rest',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 23,
        bodyPart: 'Legs',
        url: 'https://www.youtube.com/embed/sMtpyLKde5Y',
        exercise: {
            Leg_Extensions: 'AM workout (1/4) 4 sets of 10-15 reps, 90-120 sec rest',
            Leg_Press: 'AM workout (2/4) 4 sets of 10-15 reps, 90-120 sec rest',
            Hack_Squat: 'AM workout (3/4) 4 sets of 10-15 reps, 90-120 sec rest',
            Smith_Machine_Squat: 'AM workout (4/4) 7 sets of 10-15 reps, 90-120 sec rest',
            Lying_Leg_Curl: 'PM workout (1/3) 4 sets of 10-15 reps, 90-120 sec rest',
            Stiff_Legged_Dumbbell_Deadlift: 'PM workout (2/3) 4 sets of 10-15 reps, 90-120 sec rest',
            Seated_Leg_Curl: 'PM workout (3/3) 7 sets of 10-15 reps, 90-120 sec rest',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',

        },
    },
    {
        id: 24,
        bodyPart: 'Shoulders & Abs',
        url: 'https://www.youtube.com/embed/ZffU3_ftwiA',
        exercise: {
            Dumbbell_Military_Press: '4 sets of 8-10 reps, 60-90 sec rest',
            Seated_Side_Lateral_Raise: '3 sets of 8-10 reps, 60-90 sec rest',
            Barbell_Incline_Shoulder_Raise: '3 sets of 8-10 reps, 60-90 sec rest',
            Reverse_Machine_Flyes: '3 sets of 8-10 reps, 60-90 sec rest',
            Smith_Machine_Shoulder_Press: '7 sets of 8-10 reps, 60-90 sec rest',
            Barbell_Ab_Rollout: '3 sets to failure, 60-90 sec rest',
            Cross_Body_Crunch: '7 sets of 8-10 reps, 30 sec rest',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 25,
        bodyPart: 'Back',
        url: 'https://www.youtube.com/embed/jKB661p8Oxc',
        exercise: {
            Wide_Grip_Pullup: '2 sets of 10-12 reps to failure, 90-120 sec rest',
            V_Bar_Pullup: '2 sets of 10-12 reps to failure, 90-120 sec rest',
            OneArm_Dumbbell_Row: '4 sets of 8-10 reps, 90-120 sec rest',
            T_Bar_Row: '4 sets of 8-10 reps, 90-120 sec rest',
            Barbell_Shrug: '2 sets of 12-15 reps, 90-120 sec rest',
            Seated_Cable_Rows: '7 sets of 8-10 reps, 60 sec rest',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 26,
        bodyPart: 'Biceps & Calves',
        url: 'https://www.youtube.com/embed/_ln0qZ-I6Sk',
        exercise: {
            Cable_Preacher_Curl: '4 sets of 8-10 reps, 90 sec rest',
            Alernate_Incline_Dumbbell_Curl: '3 sets of 8-10 reps, 90 sec rest',
            Lying_Cable_Curl: '3 sets of 8-10 reps, 90 sec rest',
            Spider_Curl: '7 sets of 8-10 reps, 90 sec rest',
            Seated_Calf_Raise: '3 sets of 20 reps, 90 sec rest',
            Calf_Press_On_Leg_Press_Machine: '3 sets of 20 reps, 90 sec rest',
            Donkey_Calf_Raise: '7 sets of 20 reps, 30 sec rest',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 27,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/OVcIs2cX1xU',
        exercise: {
            
        },
    },
    {
        id: 28,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/LDInWclzvIo',
        exercise: {
            
        },
    },
    {
        id: 29,
        bodyPart: 'Legs & Calves',
        url: 'https://www.youtube.com/embed/r2L8ozucmk4',
        exercise: {
            Barbell_Squat: '10 sets of 10 reps, rest 60 sec',
            Leg_Extensions: '5 sets of 15 reps, rest 60-90 sec',
            Hamstring_Curl: '5 sets of 15 reps, rest 60-90 sec',
            Seated_Calf_Raise: '10 sets of 10 reps, rest 60 sec',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 30,
        bodyPart: 'Chest & Abs',
        url: 'https://www.youtube.com/embed/lgwR6Wg1d2A',
        exercise: {
            Dumbbell_Bench_Press: '10 sets of 10 reps, rest 60 sec',
            Incline_Dumbbell_Flyes: '5 sets of 10 reps, rest 60-90 sec',
            Decline_Dumbbell_Bench_Press: '5 sets of 10 reps, rest 60-90 sec',
            Weighted_Sit_Up: '10 sets of 10 reps, rest 60 sec',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 31,
        bodyPart: 'Back',
        url: 'https://www.youtube.com/embed/3UjzUZUlecw',
        exercise: {
            Weighted_Pull_Ups: '10 sets of 10 reps',
            Bent_Over_Barbell_Row: '5 sets of 5 reps',
            Barbell_Shrug: '5 sets of 20 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 32,
        bodyPart: 'Shoulders',
        url: 'https://www.youtube.com/embed/Ytl-XxFIeJ8',
        exercise: {
            Dumbbell_Shoulder_Press: '5 sets of 10 reps',
            Arnold_Dumbbell_Press: '5 sets of 10 reps',
            Side_Lateral_Raise: '5 sets of 15 reps',
            Wide_Grip_Upright_Row: '5 sets of 15 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 33,
        bodyPart: 'Biceps & Triceps',
        url: 'https://www.youtube.com/embed/E_R3q8Z2DuY',
        exercise: {
            Barbell_Curl: '5 sets of 10 reps, rest 60 sec max',
            EZ_Bar_Curl: '5 sets of 10 reps, rest 60 sec max',
            Close_Grip_Weighted_Dip: '10 sets of 10 reps, rest 60 sec max',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 34,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/9BgvG07fbyM',
        exercise: {
            
        },
    },
    {
        id: 35,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/JZxp-Ik6PYE',
        exercise: {
            
        },
    },
    {
        id: 36,
        bodyPart: 'Legs & Calves',
        url: 'https://www.youtube.com/embed/dzgqTYgkZjI',
        exercise: {
            Leg_Extensions: '2 sets of 15-20 reps',
            Leg_Press: '2 sets of 8-12 reps',
            Hack_Squat: '2 sets of 8-12 reps',
            Dumbbell_Lying_Curl: '2 sets of 8-12 reps',
            Seated_Leg_Curl: '2 sets of 10-15 reps',
            Seated_Calf_Raise: '2 sets of 8-12 reps',
            Standing_Calf_Raise: '2 sets of 8-12 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 37,
        bodyPart: 'Shoulders & Triceps',
        url: 'https://www.youtube.com/embed//Q1RqldubCz0',
        exercise: {
            Seated_Military_Press: '2 sets of 8-12 reps',
            Side_Lateral_Raise: '2 sets of 8-12 reps',
            BentOver_Rear_Delt_Raise: '2 sets of 8-12 reps',
            Reverse_Machine_Flyes: '2 sets of 8-12 reps',
            Shrug: '2 sets of 8-12 reps',
            Triceps_Pushdown: '2 sets of 8-12 reps',
            Skullcrusher: '2 sets of 8-12 reps',
            One_Arm_Triceps_Extension: '2 sets of 8-12 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 38,
        bodyPart: 'Cardio',
        url: 'https://www.youtube.com/embed/7FaIdbG79B8',
        exercise: {
        },
    },
    {
        id: 39,
        bodyPart: 'Chest & Biceps',
        url: 'https://www.youtube.com/embed/0E5FuMBHa3I',
        exercise: {
            Incline_Dumbbell_Press: '2 sets of 8-12 reps',
            Leverage_Chest_Press: '2 sets of 8-12 reps',
            Decline_Dumbbell_Bench_Press: '2 sets of 8-12 reps',
            Cable_Crossover: '2 sets of 8-12 reps',
            Dumbbell_Alternate_Bicep_Curl: '2 sets of 8-12 reps',
            Barbell_Curl: '2 sets of 8-12 reps',
            Machine_Preacher_Curl: '2 sets of 8-12 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 40,
        bodyPart: 'Back & Abs',
        url: 'https://www.youtube.com/embed/4TB0HQ52GT4',
        exercise: {
            Reverse_Grip_Lat_Pull_Down: '2 sets of 8-12 reps',
            Close_Grip_Front_Lat_Pulldown: '2 sets of 8-12 reps',
            Bent_Over_Barbell_Row: '2 sets of 8-12 reps',
            Low_Rows: '2 sets of 8-12 reps',
            One_Arm_Dumbbell_Row: '2 sets of 8-12 reps',
            Barbell_Deadlift: '2 sets of 8-12 reps',
            Cable_Reverse_Crunch: '2 sets of 8-12 reps',
            Sit_Up: '2 sets to failure',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 41,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/Osv8lqOVk6c',
        exercise: {
            
        },
    },
    {
        id: 42,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/OD6xNyzL4yE',
        exercise: {
            
        },
    },
    {
        id: 43,
        bodyPart: 'Legs & Calves',
        url: 'https://www.youtube.com/embed/Nfr1CebZPuQ',
        exercise: {
            Leg_Press: '12 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps',
            Leg_Extension: 'Superset (1/2) 6 sets of 30 25 20 15 10 5 reps',
            Seated_Leg_Curl: 'Superset (2/2) 6 sets of 30 25 20 15 10 5 reps',
            Leg_Extensions: '6 sets of 5 10 15 20 15 30 reps',
            Seated_Leg_Curls: '6 sets of 5 10 15 20 15 30 reps',
            Seated_Calf_Raise: '12 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 44,
        bodyPart: 'Chest & Biceps',
        url: 'https://www.youtube.com/embed/Kfynde2E-GE',
        exercise: {
            Preacher_curl: '6 sets of 30 25 20 15 10 5 reps',
            Decline_Dumbbell_Bench_Press: '6 sets of 30 25 20 15 10 5 reps',
            Dumbbell_Bench_Press: '6 sets of 5 10 15 20 15 30 reps',
            Barbell_Curl: '6 sets of 5 10 15 20 15 30 reps',
            Standing_Biceps_Cable_Curl: '3 sets 30 20 10 reps',
            Incline_Dumbbell_Press: '6 sets of 30 20 10 10 20 30 reps',
            Standing_Biceps_Cable_Curls: '3 sets of 10 20 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 45,
        bodyPart: 'Back & Abs',
        url: 'https://www.youtube.com/embed/U-WEqOBD224',
        exercise: {
            Bent_Over_Dumbbell_Lat_Row: '5 sets of 25 20 15 10 5 reps',
            Bent_Over_Trap_Row: '5 sets of 5 10 15 20 25 reps',
            Lat_Pull_Down: '5 sets of 25 20 15 10 5 reps',
            Straight_Arm_Pull_Down: '5 sets of 5 10 15 20 25 reps',
            Weighted_Sit_Up: '5 sets of 25 20 15 10 5 reps',
            Reverse_Crunch: '5 sets of 5 10 15 20 25 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 46,
        bodyPart: 'Shoulders',
        url: 'https://www.youtube.com/embed/FT0diEJo-lo',
        exercise: {
            Seated_Barbell_Military_Press: 'Superset (1/2) 6 sets of 30 25 20 15 10 5 reps',
            Cable_Lateral_Raise: 'Superset (2/2) 6 sets of 30 25 20 15 10 5 reps',
            Seated_Barbell_Military_Press_Reverse_Grip: '6 sets of 5 10 15 20 25 30 reps',
            Bent_Over_Cable_Lateral_Raise: '6 sets of 5 10 15 20 25 30 reps',
            Barbell_Shrug: 'Superset (1/2) 3 sets of 30 20 10 reps',
            Upright_Row: 'Superset (2/2) 3 sets of 30 20 10 reps',
            Barbell_Shrug_Behind_Back: '3 sets of 10 20 30 reps',
            Close_Grip_Upright_Row: '3 sets of 10 20 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 47,
        bodyPart: 'Triceps & Calves',
        url: 'https://www.youtube.com/embed/xFh5THlTQKc',
        exercise: { 
            Close_Grip_Bench_Press: 'Superset (1/2) 6 sets of 30 25 20 15 10 5 reps',
            Seated_Calf_Raise: 'Superset (2/2) 6 sets of 30 25 20 15 10 5 reps',
            Incline_Close_Grip_Bench_Press: '6 sets of 5 10 15 20 25 30 reps',
            Seated_Calf_Raises: '6 sets of 5 10 15 20 25 30 reps',
            Triceps_Pushdown: '6 sets of 30 25 20 15 10 5 reps',
            Lying_Dumbbell_Triceps_Extension: '6 sets of 5 10 15 20 25 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 48,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/tCiVPPd7JsA',
        exercise: {
            
        },
    },
    {
        id: 49,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/rav0urXZoQA',
        exercise: {
            
        },
    },
    {
        id: 50,
        bodyPart: 'Backs & Abs',
        url: 'https://www.youtube.com/embed/ZbiYHd1-B0k',
        exercise: {
            Chin_Up: '20 15 10 10 5 reps',
            Reverse_Grip_Lat_Pull_Down: '5 sets of 5 10 10 15 20 reps',
            Leverage_Iso_Row: 'Superset (1/2) 5 sets of 20 15 10 10 5 reps',
            Lying_Cable_Crunch: 'Superset (2/2) 5 sets of 20 15 10 10 5 reps',
            Seated_Cable_Rows: '5 sets of 5 10 10 15 20 reps',
            Cable_Crunch: '5 sets of 5 10 10 15 20 reps',
            Bent_Over_Barbell_Row: 'Superset (1/2) 5 sets of 20 15 10 10 5 reps',
            Seated_Leg_Tuck: 'Superset (2/2) 5 sets of 20 15 10 10 5 reps',
            Reverse_Grip_Bent_Over_Row: '5 sets of 5 10 10 15 20 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',

        },
    },
    {
        id: 51,
        bodyPart: 'Legs',
        url: 'https://www.youtube.com/embed/QvKi6q2q4cg',
        exercise: {
            Wide_Stance_Squat: '5 sets of 30 25 20 15 10 reps',
            Narrow_Stance_Squat: '5 sets of 5 10 15 20 25 reps',
            Hack_Squat_1: 'Superset (1/2) 5 sets of 30 25 20 15 10 reps',
            Stiffed_Legged_Barbell_Deadlift: 'Superset (2/2) 5 sets of 30 25 20 15 10 reps',
            Hack_Squat_2: '6 sets of 5 10 15 20 25 30 reps',
            Stiffed_Legged_Barbell_Deadlift_2: '6 sets of 5 10 15 20 25 30 reps',
            Dumbell_Walking_Lunge: '3 sets of 20 reps per leg',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 52,
        bodyPart: 'Chest & Calves',
        url: 'https://www.youtube.com/embed/3Y6qDVDj74k',
        exercise: {
            Incline_Dumbbell_Press: '6 sets of 30 25 20 15 10 5 reps',
            Decline_Dumbbell_Flyes: '6 sets of 5 10 15 20 25 30 reps',
            Leverage_Chest_Press: 'Superset (1/2) 6 sets of 30 25 20 15 10 5 reps',
            Single_Leg_Calf_Press: 'Superset (2/2) 6 sets of 30 25 20 15 10 5 reps',
            Peck_Deck_Fly: '6 sets of 5 10 15 20 25 30 reps',
            Calf_Press: '6 sets of 5 10 15 20 25 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 53,
        bodyPart: 'Shoulders',
        url: 'https://www.youtube.com/embed/jQ_ol-UjORM',
        exercise: {
            Dumbbell_Shoulder_Press: 'Superset (1/2) 6 sets of 30 25 20 15 10 5 reps',
            Cable_Upright_Row: 'Superset (2/2) 6 sets of 30 25 20 15 10 5 reps',
            Seated_Cable_Shoulder_Press: '6 sets of 5 10 15 20 25 30 reps',
            Front_Cable_Raise: '6 sets of 5 10 15 20 25 30 reps',
            Side_Lateral_Raise: 'Superset (1/2) 6 sets of 30 25 20 15 10 5 reps',
            Cable_Rear_Delt_Fly: 'Superset (2/2) 6 sets of 30 25 20 15 10 5 reps',
            Side_Lateral_Raise_2: '3 sets of 10 20 30 reps',
            Cable_Rear_Delt_Fly_2: '3 sets of 10 20 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 54,
        bodyPart: 'Biceps-Triceps & Abs',
        url: 'https://www.youtube.com/embed/VF_9FgvxKfY',
        exercise: {
            Skullcrusher: 'Superset (1/2) 6 sets of 30 25 20 15 10 5 reps',
            Hammer_Curl: 'Superset (2/2) 6 sets of 30 25 20 15 10 5 reps',
            Barbell_Curl: '6 sets of 5 10 15 20 25 30 reps',
            Lying_Dumbbell_Triceps_Extension: '6 sets of 5 10 15 20 25 30 reps',
            Overhead_Cable_Curl: 'Superset (1/2) 3 sets of 30 20 10 reps',
            Triceps_Pushdown_Rope_Attachment: 'Superset (2/2) 3 sets of 30 20 10 reps',
            Cable_Preacher_Curl: '3 sets of 10 20 30 reps',
            Bench_Dips: '3 sets of 10 20 30 reps',
            Decline_Reverse_Crunch: '6 sets of 30 25 20 15 10 5 reps',
            Exercise_Ball_Pulling: '3 sets of 10 20 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 55,
        bodyPart: 'Active rest',
        url: 'https://www.youtube.com/embed/Qzi5HJnKRHg',
        exercise: {
            
        },
    },
    {
        id: 56,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/Yk9yU0oe968',
        exercise: {
            
        },
    },
    {
        id: 57,
        bodyPart: 'Legs & Calves',
        url: 'https://www.youtube.com/embed/Szau0sBcvnk',
        exercise: {
            Leg_Extension: '3 sets of 50 40 30 reps',
            Leg_Press: '5 sets 30 25 20 15 10 reps',
            Hack_Squat: '5 sets of 10 15 20 25 30 reps',
            Leg_Extensions: '3 sets of 30 40 50 reps',
            Lying_Leg_Curl: '5 sets of 50 40 30 reps',
            Stiff_Legged_Deadlift: '5 sets of 30 25 20 15 10 reps',
            Seated_Hamstring_Curl : '5 sets of 10 15 20 25 30 reps',
            Seated_Calf_Raise: '5 sets of 30 25 20 15 10 reps',
            Standing_Calf_Raise: '5 sets of 10 15 20 25 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 58,
        bodyPart: 'Back & Chest',
        url: 'https://www.youtube.com/embed/f22hYbKfvRs',
        exercise: {
            Dumbbell_Bench_Press: 'Superset (1/2) 5 sets of 30 25 20 15 10 reps',
            T_Bar_Row: 'Superset (2/2) 5 sets of 30 25 20 15 10 reps',
            Incline_Dumbbell_Flyes: 'Superset (1/2) 3 sets of 10 20 30 reps',
            Bent_Over_Row: 'Superset (2/2) 3 sets of 10 20 30 reps',
            Lat_Pull_Down: 'Superset (1/2) 5 sets of 30 25 20 15 10 reps',
            Dip: 'Superset (2/2) 5 sets of 30 25 20 15 10 reps',
            Cable_Crossover: 'Superset (1/2) 3 sets of 10 20 30 reps',
            Cardio: 'Superset (2/2) 3 sets of 10 20 30 reps, 15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 59,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/Gp1HY_lD0qg',
        exercise: {
            
        },
    },
    {
        id: 60,
        bodyPart: 'Shoulders & Abs',
        url: 'https://www.youtube.com/embed/nHthgzBDCmw',
        exercise: {
            Dumbbell_Side_Raise: 'Superset (1/2) 5 sets of 30 25 20 15 10 reps',
            Weight_Plate_Front_Raise: 'Superset (2/2) 5 sets of 30 25 20 15 10 reps',
            Standing_Dumbbell_Shoulder_Press: 'Superset (1/2) 10 15 20 25 30 reps',
            Chest_Supported_Dumbbell_Front_Raise: 'Superset (2/2) 10 15 20 25 30 reps',
            Bent_Over_Rear_Delt_Raise: 'Superset (1/2) 5 sets of 30 25 20 15 10 reps',
            Weighted_Sit_Up: 'Superset (2/2) 5 sets of 30 25 20 15 10 reps',
            Pec_Dec_Rear_Delt_Fly: 'Superset (1/2) 5 sets 10 15 20 25 30 reps',
            Bent_Knee_Hip_Raise: 'Superset (2/2) 5 sets 10 15 20 25 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 61,
        bodyPart: 'Biceps & Triceps',
        url: 'https://www.youtube.com/embed/xXh4XpK3VOo',
        exercise: {
            Standing_Dumbbell_Triceps_Extension: 'Superset (1/2) 5 sets of 30 25 20 15 10 reps',
            Seated_Dumbbell_Curl: 'Superset (2/2) 5 sets of 30 25 20 15 10 reps',
            Decline_Dumbbell_Curl: 'Superset (1/2) 5 sets 10 15 20 25 30 reps',
            Spider_Curl: 'Superset (2/2) 5 sets 10 15 20 25 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 62,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/58vaCVJaVbs',
        exercise: {
            
        },
    },
    {
        id: 63,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/xw6dpplbHKM',
        exercise: {
            
        },
    },
    {
        id: 64,
        bodyPart: 'Legs & Calves',
        url: 'https://www.youtube.com/embed/2NI9HpXBllE',
        exercise: {
            Box_Squat: '12 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps',
            Leg_Extension: '3 sets of 50 reps',
            Hack_Squat: '2 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps',
            Leg_Curl: '3 sets of 50 reps',
            Stiff_Legged_Deadlift: '12 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps',
            Single_Leg_Calf_Press: '12 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps per leg',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 65,
        bodyPart: 'Chest & Triceps',
        url: 'https://www.youtube.com/embed/w0XCoNzFkQ4',
        exercise: {
            Incline_Bench_Press: '6 sets of 30 25 20 15 10 5 reps',
            Bench_Press: '6 sets of 5 10 15 20 25 30 reps',
            Decline_Dumbbell_Fly: '12 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps',
            Incline_Dumbbell_Fly: '6 sets of 5 10 15 20 25 30 reps',
            Rope_Triceps_Push_Down: '6 sets of 30 25 20 15 10 5 reps',
            Overhead_Triceps_Extension: '6 sets of 5 10 15 20 25 30 reps',
            Close_Grip_Push_Up: '6 sets of 30 25 20 15 10 5 reps',
            Bench_Dip: '6 sets of 5 10 15 20 25 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 66,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/werWAjyyJEs',
        exercise: {
            
        },
    },
    {
        id: 67,
        bodyPart: 'Back & Biceps',
        url: 'https://www.youtube.com/embed/9Os4MwSWkiI',
        exercise: {
            Neutral_Grip_Pull: 'Alernating set(1/2) 3 sets of 25 15 5 reps',
            Chin_Up: 'Alernating set(1/2) 3 sets of 25 15 5 reps',
            Reverse_Grip_Lat_Pull_Down: '3 sets of 5 10 15 reps',
            Close_Grip_Lat_Pulldown: '3 sets of 20 25 30 reps',
            Reverse_Grip_Bent_Over_Barbell_Row: '5 sets of 25 20 15 10 5 reps',
            Bent_Over_Barbell_Row: '5 sets of 5 10 15 20 25 reps',
            Single_Arm_Dumbbell_Arc_Row: '5 sets of 25 20 15 10 5 reps',
            Single_Arm_Dumbbell_Row: '5 sets of 5 10 15 20 25 reps',
            Preacher_curl: '5 sets of 25 20 15 10 5 reps',
            Single_Arm_Preacher_Curl: '5 sets of 5 10 15 20 25 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 68,
        bodyPart: 'Shoulders',
        url: 'https://www.youtube.com/embed/cJ8pjK_rxIQ',
        exercise: {
            Smith_Machine_Shoulder_Press: '12 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps',
            Reverse_Fly: '6 sets of 30 25 20 15 10 5 reps',
            Neutral_Grip_Reverse_Fly: '6 sets of 5 10 15 20 25 30 reps',
            Standing_Dumbbell_Side_Raise: '6 sets of 30 25 20 15 10 5 reps',
            Seated_Dumbbell_Side_Raise: '6 sets of 5 10 15 20 25 30 reps',
            Barbell_Shrug: '6 sets of 25 20 15 10 5 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 69,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/tQwmipJT0rw',
        exercise: {
            
        },
    },
    {
        id: 70,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/bk9Xuc_H0Zw',
        exercise: {
            
        },
    },
    {
        id: 71,
        bodyPart: 'Legs',
        url: 'https://www.youtube.com/embed/7aXcU4LsFxI',
        exercise: {
            Leg_Extension: 'Gaint set (1/3) 5 sets of 30 reps',
            Leg_Press: 'Gaint set (2/3) 5 sets 30 25 20 15 10 sets of reps',
            Hack_Squat: 'Gaint set (3/3) 5 sets 30 25 20 15 10 sets of reps',
            Seated_Hamstring_Curl: 'Gaint set (1/3) 5 sets of 30 reps',
            Leg_Press_2: 'Gaint set (2/3) 5 sets 30 25 20 15 10 sets of reps',
            Hack_Squat_2: 'Gaint set (3/3) 5 sets 30 25 20 15 10 sets of reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 72,
        bodyPart: 'Chest & Triceps',
        url: 'https://www.youtube.com/embed/cjcrD8Yo3fI',
        exercise: {
            Dumbbell_Bench_Press: 'Gaint set (1/3) 5 sets 30 25 20 15 10 sets of reps',
            Incline_Dumbbell_Flyes: 'Gaint set (2/3) 5 sets 30 25 20 15 10 sets of reps',
            Cable_Crossover: 'Gaint set (3/3) 5 sets 30 25 20 15 10 sets of reps',
            Cable_Crossover_2: 'Gaint set (1/3) 5 sets 10 15 20 25 30 sets of reps',
            Incline_Dumbbell_Flyes_2: 'Gaint set (2/3) 5 sets 10 15 20 25 30 sets of reps',
            Dumbbell_Bench_Press_2: 'Gaint set (3/3) 5 sets 10 15 20 25 30 sets of reps',
            Triceps_Pushdown_V_Bar_Attachment: 'Gaint set (1/3) 5 sets 30 25 20 15 10 sets of reps',
            Triceps_Overhead_Extension_With_V_Bar: 'Gaint set (2/3) 5 sets 30 25 20 15 10 sets of reps',
            Triceps_Pushdown_Rope_Attachment:  'Gaint set (3/3) 5 sets 30 25 20 15 10 sets of reps',
            Triceps_Pushdown_Rope_Attachment_2: 'Gaint set (1/3) 5 sets 10 15 20 25 30 sets of reps',
            Triceps_Overhead_Extension_With_V_Bar_2: 'Gaint set (2/3) 5 sets 10 15 20 25 30 sets of reps',
            Triceps_Pushdown_V_Bar_Attachment_2: 'Gaint set (3/3) 5 sets 10 15 20 25 30 sets of reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 73,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/honhZ1pMARw',
        exercise: {
            
        },
    },
    {
        id: 74,
        bodyPart: 'Back & Biceps',
        url: 'https://www.youtube.com/embed/r7K4EzeN3AY',
        exercise: {
            Wide_Grip_Lat_Pulldown: 'Gaint set (1/3) 4 sets of 25 20 15 10 reps',
            Barbell_Deadlift: 'Gaint set (2/3) 4 sets of 25 20 15 10 reps',
            Chest_Supported_Dumbbell_Row: 'Gaint set (3/3) 4 sets of 25 20 15 10 reps',
            Chest_Supported_Dumbbell_Row_2: 'Gaint set (1/3) 4 sets of 10 15 20 25 reps',
            Barbell_Deadlift_2: 'Gaint set (2/3) 4 sets of 10 15 20 25 reps',
            Wide_Grip_Lat_Pulldown_2: 'Gaint set (3/3) 4 sets of 10 15 20 25 reps',
            Barbell_Curl: 'Gaint set (1/3) 4 sets of 25 20 15 10 reps',
            Standing_Biceps_Cable_Curl: 'Gaint set (2/3) 4 sets of 25 20 15 10 reps',
            High_Pulley_Curl: 'Gaint set (3/3) 4 sets of 25 20 15 10 reps',
            High_Pulley_Curl_2: 'Gaint set (1/3) 4 sets of 10 15 20 25 reps',
            Standing_Biceps_Cable_Curl_2: 'Gaint set (2/3) 4 sets of 10 15 20 25 reps',
            Barbell_Curl_2: 'Gaint set (3/3) 4 sets of 10 15 20 25 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 75,
        bodyPart: 'Shoulders-Calves & Abs',
        url: 'https://www.youtube.com/embed/jUtH26iZ7MA',
        exercise: {
            Upright_Barbell_Row: 'Gaint set (1/3) 5 sets of 30 25 20 15 10 reps',
            Standing_Military_Press: 'Gaint set (2/3) 5 sets of 30 25 20 15 10 reps',
            Alternating_Deltoid_Raise: 'Gaint set (3/3) 5 sets of 30 25 20 15 10 reps',
            Alternating_Deltoid_Raise_2: 'Gaint set (1/3) 5 sets of 10 15 20 25 30 reps',
            Standing_Military_Press_2: 'Gaint set (2/3) 5 sets of 10 15 20 25 30 reps',
            Upright_Barbell_Row_2: 'Gaint set (3/3) 5 sets of 10 15 20 25 30 reps',
            Seated_Calf_Raise: 'Superset (1/2) 6 sets of 30 20 10 10 20 30 reps',
            Tuck_Crunch: 'Superse (2/2) 6 sets to failure',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 76,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/8rkSyC9OMpY',
        exercise: {
            
        },
    },
    {
        id: 77,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/QBzfY6HTPZk',
        exercise: {
            
        },
    },
    {
        id: 78,
        bodyPart: 'Legs',
        url: 'https://www.youtube.com/embed/dkj6ytd1qjw',
        exercise: {
            Leg_Press: '10 sets of 30 25 20 15 10 10 15 20 25 30 reps',
            Bulgarain_Split_Squat: '5 sets of 30 25 20 15 10 reps',
            Smith_Machine_Split_Squat: '5 sets of 30 25 20 15 10 reps',
            Calf_Press: '5 sets of 30 25 20 15 10 reps',
            Standing_Calf_Press: '5 sets of 10 15 20 25 30 reps',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 79,
        bodyPart: 'Back & Chest',
        url: 'https://www.youtube.com/embed/MFW9MTrT32Y',
        exercise: {
            Leverage_Chest_Press: 'Superset (1/2) 10 sets of 30 25 20 15 10 10 15 20 25 30 reps per arm',
            Chest_Supported_Dumbbell_Row: 'Superset (2/2) 10 sets of 25 20 15 10 10 15 20 25 reps per arm',
            One_Arm_Lat_Pulldown: 'Superset (1/2) 6 sets of 25 15 5 5 15 25 reps',
            Single_Arm_Cable_Crossover: 'Superset (2/2) 6 sets of 25 15 5 5 15 25 reps', 
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 80,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/hAB_4cgWd6U',
        exercise: {
            
        },
    },
    {
        id: 81,
        bodyPart: 'Shoulders & Abs',
        url: 'https://www.youtube.com/embed/kCqYJUgPFkI',
        exercise: {
            Dumbbell_One_Arm_Shoulder_Press: 'Superset (1/2) 10 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps per arm',
            One_Arm_Side_Lateral_Raise: 'Superset (2/2) 10 sets of 30 25 20 15 10 5 5 10 15 20 25 30 reps per arm',
            BentOver_Cable_Rear_Delt_Raise: 'Superset (1/2) 3 sets of 30 20 10 reps per arm',
            Cable_Reverse_Crunch: 'Superset (2/2) 3 sets to absolute failure',
            BentOver_Cable_Rear_Delt_Raise_2: 'Superset (1/2) 3 sets of 10 20 30 reps per arm',
            Sit_Up: 'Superset (2/2) 3 sets to absolute failure',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 82,
        bodyPart: 'Biceps & Triceps',
        url: 'https://www.youtube.com/embed/TnB4csvsBI0',
        exercise: {
            Single_Arm_Cable_Biceps_Curl: 'Superset (1/2) 10 sets of 30 25 20 15 10 10 15 20 25 30 reps per arm',
            Single_Arm_Cable_Triceps_Kickback: 'Superset (2/2) 10 sets of 30 25 20 15 10 10 15 20 25 30 reps per arm',
            Single_Arm_Cable_Biceps_Curl_2: 'Superset (1/2) 6 sets of 30 20 10 10 20 30 reps each arm',
            Single_Arm_Cable_Triceps_Kickback_2:  'Superset (2/2) 6 sets of 30 20 10 10 20 30 reps each arm',
            Cardio: '15-minute intervels: 3 min easy, 1 min hard',
        },
    },
    {
        id: 83,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/wzWw7-UsrmY',
        exercise: {
            
        },
    },
    {
        id: 84,
        bodyPart: 'Active Rest',
        url: 'https://www.youtube.com/embed/gLT4EQbkIKg',
        exercise: {
            
        },
    },

]

export default Days;